### ISSUE TITLE
undoMove and redoMove need refactoring

### ISSUE THREAD

**Issue by MohamedZalat** [AdamPrins/JumpIN#30]
Duplicated code in the two methods.

Checkout the command pattern.

**Comment by EveningStarlight** [comment]
I am looking for clarification on this issue. 

Since I can see how I can combine that two methods, but it require a method that takes 4 arguments: the two stacks, and both of the move's coordinates. and it would still need to be inside of the if (stack.isEmpty()).
This is because undo and redo handle the moves slightly differently. (Undo selects the new and swaps with the old, where as redo selects the old and swaps with new.
I feel this abstracts the functions too much and makes the code more obtuse than the current implementation. 

The other option would be only simplifying the middle two select and swap lines. But I feel like that is reduction than you had originally intended.

**Comment by MohamedZalat** [comment]
As long as the code doesnt have repeated logic, then you should be fine. You have the correct idea in your first paragraph as the logic is the same except the stacks are swapped.


________________________________

**Comment by EveningStarlight** [comment]
So you are of the opinion that it would be better implemented with the following code:

	 /**
	 * undoes the last move made as described on the undoStack
	 */
	public void undoMove() {
		if (undoStack.isEmpty()) {
			throw new IllegalArgumentException("There is nothing to undo");
		}
		else {
			stackControl(undoStack, redoStack, undoStack.peek().COORD_NEW, undoStack.peek().COORD_OLD);
		}
	}

	/**
	 * redoes the next move made as described on the redoStack
	 */
	public void redoMove() {
		if (redoStack.isEmpty()) {
			throw new IllegalArgumentException("There is nothing to redo");
		}
		else {
			stackControl(redoStack, undoStack, redoStack.peek().COORD_OLD, redoStack.peek().COORD_NEW);
		}
	}
	
	/**
	 * Handles the movement moving from one stack to the other stack
	 * 
	 * @param origin undo/redo stack we are popping from
	 * @param destination undo/redo stack we are popping to
	 * @param selection coordinate of the piece
	 * @param swap coordinate of the destination
	 */
	private void stackControl(Stack<Move> origin, Stack<Move> destination, Coord selection, Coord swap) {
		selectedTile=this.getTile(selection);
		swapPiece(swap, false);
		destination.add(origin.pop());
	}

**Comment by MohamedZalat** [comment]
Yes, that is correct.

________________________________

**Comment by EveningStarlight** [comment]
Code is implemented and passes all test cases still
